= Teak for Developers
:page-aliases: /home/developers.adoc

== Quick Start

If you know where you're going already, and want to jump right in, here's your links.

=== Client Developers

* xref:android::page$integration.adoc[Native Android]
* xref:ios::page$integration.adoc[Native iOS]
* xref:unity::page$quickstart/index.adoc[Unity]

=== Server Developers

If you're a server developer that needs to implement the reward endpoint, here's what you need:

* xref:server-api::page$rewards/endpoint.adoc[Reward Endpoint]

== Before You Start

Before you start working with Teak there's a few things you'll want to have ready to streamline the process.

== Your Game

You'll need a game to integrate, on iOS, Android or Facebook and a way to test new builds of it. A great deal of debugging information is written to the log window, so you'll want to make sure you can look at the device log.

=== Unity Pre-Requisites

If you build your game using Unity you will need to be able to do a few things for Android projects.

NOTE: If your Unity-based game is iOS only you can safely skip this section.

==== Android

If your game is available on Android, you will need some way to add things to an Android Manifest. This is frequently done in one of two ways:

* A manifest that is located at `Assets/Plugins/Android/AndroidManifest.xml`
* A manifest that is merged in by a custom Gradle build

You will also need a way to add dependencies to your project. This is frequently done in one of two ways:

* Using the  xref:unity::page$play-services-resolver.adoc[External Dependency Manager for Unity, window=_blank]
* A custom Gradle build that contains dependencies in the project's Gradle file.

=== Unity Integration

Finally, here's everything you need for xref:unity::page$quickstart/index.adoc[Teak Integration in the Unity Editor].

=== Native iOS

If you are building a native iOS game, you will need to be able to:

* Add things to your `Info.plist`
* Add dependencies to your project

Both of these are easily accomplished inside Xcode.

Here's the rest of what you need for xref:ios::page$integration.adoc[Integrating Teak on Native iOS].

=== Native Android

If you are building a native Android game, you will need to be able to:

* Add things to your `AndroidManifest.xml`
* Add dependencies to your `build.gradle`

Both of these are easily accomplished via Android Studio or a text editor.

Here's the rest of what you need for xref:android::page$integration.adoc[Integrating Teak on Native Android].

include::partial$push-credentials.adoc[leveloffset=+1]
