= Email

Email is set up in the same flow as Push Notifications. Click menu:Notifications[Email Tab, New Message] to create a new message. Make sure the *Email* option is checked. 

== Templates 

There are currently 2 ways to build an email on Teak. You can find these options in the *Templates* dropdown. 

Large Image Click:: 
This is the default template. This template prioritizes having a large image that players tap to launch the game. 

Custom HTML::
For advanced users to create their own email layouts.

== Using _"Large Image Click"_

Teak's default template is optimized to get players in the game. It features a small text area, followed by a large clickable image that launches the game. This image can be incentivized using the Rewards system. 

=== Subject
_50 Characters Recommended. 255 Characters allowed._

The subject line of the email. This is the first thing a player will see, so getting this right is key to good Open rates and CTR.


=== Preview Text
_Recommended between 30 to 100 characters._

This text appears in the inbox preview of the email client, but not in the body of the email. Typically, this is displayed right under the subject line and slightly grayed out. Different email clients display this differently. 

This may also be referred to as a “preheader” or “hidden preheader” in other email systems. 


=== Message
_768 Characters allowed (Keeping a balanced Text to Image ratio and including HTML and Tags)_

This text appears at the top of the email above the big image. 

You can use the same tags, emojis, and HTML formatting in Email that you can on Android. You can use the Teak Markup Tag documentation, but any HTML5 is acceptable.

=== Image

The _Large Image Click_ template requires an image to be sent. We recommend _800x800 px_ images as a starting point, but the image size is mostly up to you, and will be compressed as needed. It’s beneficial to test on different devices and email providers to determine the ideal resolution for your images.

Animated .gif files can be used in your emails, but keep in mind that their large size may cause loading issues if displayed on older devices or slow connections. Additionally, they won’t be displayed at all to players using Outlook as their email client. These can be highly engaging, but should be tested thoroughly on your app's min spec devices.

==== Image Alt-Text

Many email clients hide images by default, so make sure to include alt-text for the image, to give players a reason to tap, even if they don't have images turned on.

== Rewards

As with Notifications, adding Rewards is just a couple of clicks away. Once you’ve created the Bundle, you simply apply it to your message with the "Reward Bundle" dropdown.  Bundles are reusable, so you only have to set each distribution once, and you can use it on any Message, Email, or Link. If you choose not to incentivize your message, do not choose an option, or click the "X" to the right of the selected Bundle to remove it.

=== Expiration

Setting an Expiration time on rewards helps to ensure an economic balance in your game. Knowing how many Links, Messages, and Emails are active at any given time can help your team estimate how much free currency will be available, and prevent players from mass collections.

Email rewards allow you to set an expiration based in minutes, hours, or days after the send time.

== Link Destination

Control where the player is taken after a click or tap on an email link.

Game Launch::
Taps and clicks on the email link will attempt to launch the game, and any associated rewards will be granted.
+
If the game is not installed on mobile devices, the player will be taken to the game listing in the appropriate app store for that device. (The app store link is based on the iTunes Product ID or Android Package Name configured in the game settings.)
+
If an email link is clicked on a desktop device, the player will be taken to the Desktop Game URL set in the game settings.

Game Deep Link::
Direct players to a specific location in your game with a xref:unity::teak-unity-features.adoc#_deep_links[Deep Link, window=_blank] route.
+
When the player taps the notification, the game will launch if it is installed on the device. But, instead of beginning at the default screen, players start their session in another location in the game, such as their inbox, a store, or a specific moment in their progression, and any associated rewards will be granted.
+
To use Deep Links, your team needs to integrate Teak's xref:unity::teak-unity-features.adoc#_deep_links[Deep Linking, window=_blank]. It's best practice to confirm with a developer what routes and values are available.

Out of Game URL::
Link to an out of game destination with a web URL (e.g. `https&#58;//example.com/`).
+
When the player taps the email link on **Android** or **iOS**, the game will launch and then open the default browser to the URL. Any associated rewards will be granted before the browser is opened. When the player clicks the email link on **Desktop** the game will launch, but the player will __not__ be redirected to the Out of Game URL due to browser security restrictions.
+
This behavior can be overridden with Skip Game Open.

=== Skip Game Open

For email only, there is an option to skip the game open when opening an Out of Game URL.

When this option is enabled, the game will not be opened when the link is tapped in an email. Instead, the player will be taken directly to the configured URL. Rewards cannot be granted when the game open is skipped. Clicks will be tracked, and if a player opens the game on the same device within an hour of click, they will be tracked as a xref:usage:reference:page$notification-metrics.adoc#_email_returning_user[Returning User, window=_blank] for the email.

////
== Advanced

Deep Link::
This option allows you to direct players to a specific location in your game. When this feature is used, players will click the Email and the game will launch. Instead of beginning at the default screen, you can have players begin their session in another location in the game, such as their inbox, a store, or a specific moment in their progression. Any rewards will be awarded as normal.

A specific difference If you have both mobile and desktop experiences is that *you will only be able to use a Deep Link for one of these options per Email.* You may set the Deep Link for Mobile OR Desktop. The players who do not open where the Deep Linking is available will have their games opened to the default entry point, and will receive any Rewards as normal.

*Example*: If the Deep Link is routed for mobile, but the message is opened on desktop, it will not go to the routed entry point, but will open as if there were no Deep Link, and apply the Rewards.

You can try to mitigate this by splitting your Audience by mobile or desktop and send an Email with the corresponding Deep Links. You may still have some players who slip through the cracks.
////

== Testing

When optimizing Messages, Teak makes performing A/B and Multivariate tests easy. During the Email creation process, choose the "Create A/B Test" option. You can create dozens of Emails to be distributed. From here you can change the content or the incentives as well as the Reward expiration and Advanced options.

At the time the test is set up, Teak will randomly assign players from the audience to the variants.

When you go back to the Email tab, you have more options for your test. +
You can: +

Select a Winner:: Disable the other tests and remove them from the UI.

Configure Test:: Choose the weight of each test variable or randomize your audience. If you are running this message as a Recurring message this helps to ensure players are not only getting one variant if they remain in the audience.

NOTE: You will have to make this adjustment on each platform the test will run on and it will randomize every 24 hours.

== Preview

Once you have your Email message created and bundles added, you can verify it by sending a test message.

.Previewing an Email

. Select "Notifications" from the left rail
. Enter the "Email" Tab
. Locate the Email
. Select "Preview" on the right.

This will send to the Email address associated with your account. Previewing on different platforms and resolutions will help give the most clear picture of how your Email will appear for players.

NOTE: This requires a player to be registered with the email address where you want to receive the test message.

== Emails That Can Be Replied To

In Email Settings, create a new Email Credential using the same Sendgrid API Key as your normal Email Credential.

If, and only if, you have set up the domain of the email address you want replies to go to as an authenticated domain for your SendGrid account, you may set that email address as the From Address.

However, if you have not - or cannot do that - use the same From Address as your normal Email Credential.

In this case, set the email address you want replies to go to as the Reply To Address on the Email Credential.

Once this Email Credential is created, you can use it on a Schedule by Schedule basis. To do this, when setting up a Schedule with a Message that has Email content, you will have an option for "Override Email Credential for send". Set this to your newly created Email Credential.

Now, when this Schedule is used to send an Email, if a player replies to the Email from their email client, the reply will be sent to the configured "Reply To Address". Schedules which do not have Override Email Credentials for send will continue to use the default From and Reply To Addresses, which are typically "noreply".
