= Welcome!
:page-aliases: /home/index.adoc
:page-no-toc: true
:!page-pagination:

Teak is the CRM that understands free-to-play games. We give your team easy-to-use push notifications, effective emails, and shareable links that can all be rewarded. All this to give your players what they want the most: more playtime.

== Getting Started

[cols="2", role="nav-table", frame="none", grid="none"]
|===
a|

[.iconblock]
====
image::book.svg[Guide Icon,50,xref=ROOT:user-guide:page$index.adoc]

xref:ROOT:user-guide:page$index.adoc[*User Guide*] +
Setup and use the Teak Dashboard
====

a|


[.iconblock]
====
image::piratebook.svg[Dev Guide Icon,50,xref=developer-quickstart.adoc]

xref:developer-quickstart.adoc[*Developer Guide*] +
Integrate the Teak SDKs
====

a|

[.iconblock]
====
image::question.svg[FAQ Icon,50,xref=faq.adoc]

xref:ROOT::faq.adoc[*FAQ*] +
Frequently Asked Questions
====

a|

[.iconblock]
====
image::medic.svg[Support Icon,50,xref=support.adoc]

xref:ROOT::support.adoc[*Support*] +
Get help from the Teak Team
====

|===

== Developer Quickstart
Integrate the Teak SDK

[cols="3", role="nav-table", frame="none", grid="none"]
|===
a|

[.iconblock]
====
image::unity.svg[Unity Logo,50,xref=unity::page$quickstart/index.adoc]

xref:unity::page$quickstart/index.adoc[*Unity SDK Quickstart*] +
====

a|

[.iconblock]
====
image::terminal.svg[Server API Icon,50,xref=server-api::page$index.adoc]

xref:server-api::page$index.adoc[*Server API*]
====

a|

[.iconblock]
====
image::tools.svg[Tool Icon,50,xref=developer-quickstart.adoc#_client_sdks]

xref:ROOT::page$developer-quickstart.adoc#_client_sdks[*Other SDKs*]
====

|===


'''

[.align-center]
©{docyear} Teak.io
