= Welcome!
:page-aliases: /home/index.adoc
:page-no-toc: true
:!page-pagination:

Teak is the CRM that understands free-to-play games. We give your team easy-to-use push notifications, effective emails, and shareable links that can all be rewarded. All this to give your players what they want the most: more playtime.

== Getting Started

[cols="2", role="nav-table", frame="none", grid="none"]
|===
a|

[.sidebarlink]
****
xref:ROOT:user-guide:page$index.adoc[*User Guide*] +
Setup and use the Teak Dashboard
****

a|


[.sidebarlink]
****
xref:developer-quickstart.adoc[*Developer Guide*] +
Integrate the Teak SDKs
****

a|

[.sidebarlink]
****
xref:unity::quickstart/hello-world.adoc[*Push Notification Quickstart*] +
Creating and sending your first Push
****

a|

[.sidebarlink]
****
xref:faq.adoc[*FAQ*] +
Frequently Asked Questions
****

|===

== Developer Quickstart
Integrate the Teak SDK

[cols="3", role="nav-table", frame="none", grid="none"]
|===
a|

[.iconblock]
====
image::unity.svg[Unity Logo,50,xref=unity::page$quickstart/index.adoc]

xref:unity::page$quickstart/index.adoc[*Unity SDK Quickstart*] +
====

a|

[.iconblock]
====
image::terminal.svg[Server API Icon,50,xref=server-api::page$index.adoc]

xref:server-api::page$index.adoc[*Server API*]
====

a|

[.iconblock]
====
image::support.svg[Server API Icon,50,xref=support.adoc]

xref::page$support.adoc[*Support*]
====

|===


'''

Last modified: **{docdatetime}**
