= Reporting

There are several ways to aggregate information for reporting in Teak. 

== Available Metrics

=== Primary Dashboard
_Accessed by selecting “Dashboard” from the left rail._ +
This covers all game metrics and has many tabs to be explored. You can review the overall health of your app and compare it to campaign performance. There are geo and date filters in the upper right.

=== Notification Dashboard
_Accessed by selecting “Notifications” from the left rail and viewing the “Settings” Tab._ +
This is specific to the results of your Push, App-to-User and Email campaigns. Adjusting the date also adjusts the results on the individual schedules and messages below the dashboard. If you have questions about the definitions of specific items, please review the Glossary for more information.

== Analyzing

Within Notifications, you can do additional analysis. Select the Table view from the options to the left of the Sort button. Now, you may Filter and Sort the data to prepare it for export. Within the tabs for the individual notification platforms, you can choose to show a breakdown of the audience by the reward received. This can be found under Filters and selecting “Show Audience Reward”. 

== Exporting

While in Table view, you may choose to download a .CSV of the visible data. There is a Download button to the left of the first column header. The data can then be aggregated further in your spreadsheet software of choice. 
