version: 2.1

orbs:
  teak: teak/sdk-utils@0.7.0

parameters:
  build_type:
    type: enum
    default: "development"
    enum: ["development", "production"]

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - teak/build-antora-playbook:
          build_type: << pipeline.parameters.build_type >>

workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - Antora
