= Reporting
:page-aliases: usage:reporting.adoc

There are several ways to aggregate information for reporting in Teak.

== Available Metrics

=== Primary Dashboard
_Accessed by selecting "Dashboard" from the left rail._ +
This covers all game metrics and has many tabs to be explored. You can review the overall health of your app and compare it to campaign performance. There are geo and date filters in the upper right.

=== Notification Dashboard
_Accessed by selecting "Notifications" from the left rail and viewing the "Settings" Tab._ +
This is specific to the results of your Push, App-to-User and Email campaigns. Adjusting the date also adjusts the results on the individual schedules and messages below the dashboard. If you have questions about the definitions of specific items, please review the Glossary for more information.

== Analyzing

Within Notifications, you can do additional analysis. Select the Table view from the options to the left of the Sort button. Now, you may Filter and Sort the data to prepare it for export. Within the tabs for the individual notification platforms, you can choose to show a breakdown of the audience by the reward received. This can be found under Filters and selecting "Show Audience Reward".

=== Selecting a Date Range

The date range of metrics in Teak are controlled by the date picker in the top bar. By default, this is set to the last 14 days.

Changing the date range will update all metrics in the dashboard to only include data from the selected time period. This is useful for reporting data for a particular month or quarter.

=== Filtering

All data lists in Teak have a filter dropdown. This can be useful for narrowing down the data you are pulling for a report.

Since metrics are only shown for the current time range, older notifications will be shown as having zero data. *Hide Zero Clicks* is useful for hiding those entries when pulling data for a report.

If you want to know how your automated campaigns are doing, select *Repeating* from the filter dropdown to only see data for those notifications.


=== Searching

All data lists have a search field. The search terms are separated by a space, but can also be enclosed in double quotes for exact phrase searching.

Searching for, _Lucky Slots_, will find anything with _Lucky_, *AND* _Slots_. While searching for, _"Lucky Slots"_, will only find items with the whole phrase, _Lucky Slots_.

Planning your names and descriptions to be search friendly can save you time when reporting. We recommend using the *YYYY.MM.DD* format for dates included in names. This will make searching and sorting easier for future you.

== Exporting

While in Table view, you may choose to download a .CSV of the visible data. There is a Download button to the left of the first column header. The data can then be aggregated further in your spreadsheet software of choice.
