= Link Metrics
These are the metrics Teak tracks for links with a description of what causes Teak to track each given metric.

:channel: link

Rewards Claimed::
If the link has a reward bundle associated, this will be the count of times the reward was claimed from this {channel}, regardless of the selected time frame. If the link has no reward bundle associated then this metric will not be present.

Clicks::
A click is tracked when a player enters the game through the link. Note that the game must get through complete Teak SDK initialization before a click event will be tracked.

Returning Users::
include::partial$returning_users.adoc[]

Return Value::
include::partial$return_value.adoc[]

Return Spenders::
include::partial$return_spenders.adoc[]

Return Value per Spender::
Return Value per Spender is return value / return spenders.

New Users::
New Users is the count of players that Teak saw for the first time in a session attributed to the {channel}. Seeing a player for the first time means that Teak has never previously seen the game assigned player id for the game or the associated Facebook App Scoped ID if provided.

Install Value::
Install Value is the sum of revenue from _all_ New Users from this {channel} during the currently selected time frame. E.g. If the currently selected time frame is Jul 16, 2021 - Jul 29, 2021, then a player counted as a New User for the {channel} on January 1, 2019 who spent $9.99 on July 17, 2021 would be counted as Install Value in the display.
