= Notification Metrics

These are the metrics Teak tracks for notifications with a description of what causes Teak to track each given metric.

TIP: Not every metric is visible by default. Change to Compact or Table View to see all available metrics.

:channel: notification

== Schedules

Sends::
A send is tracked when the underlying messaging service indicates that it will attempt to deliver a notification to a player.

Clicks::
A click is tracked when a player enters the game through a notification. Note that the game must get through complete Teak SDK initialization before a click event will be tracked.

CTR::
Schedule CTR is clicks / sends as a percentage.

Returning Users::
include::partial$returning_users.adoc[]

Return Value::
include::partial$return_value.adoc[]

Return Spenders::
include::partial$return_spenders.adoc[]

Return Value per Spender::
Return Value per Spender is Return Value / Return Spenders.

Avg. Daily Play Time::
The average amount of time spent per day in sessions which started from a click on this notification per player who clicked. +
_(Only available with SDK 4.3 and above.)_

== Facebook A2U

Sends::
A send is tracked when Facebook indicates that it will attempt to deliver a notification to a player.

Clicks::
A click is tracked when a player enters the game through a Facebook A2U notification. Note that the game must get through complete Teak SDK initialization before a click event will be tracked.

CTR::
Facebook A2U CTR is clicks / sends as a percentage.

Returning Users::
include::partial$returning_users.adoc[]

Return Value::
include::partial$return_value.adoc[]

Return Spenders::
include::partial$return_spenders.adoc[]

Impact::
Impact is Returning Users for the notification divided by the sum of all sends for all Facebook A2U notifications.

Avg. Daily Play Time::
The average amount of time spent per day in sessions which started from a click on this notification per player who clicked. +
_(Only available with SDK 4.3 and above.)_

== iOS Push

Sends::
A send is tracked when the Apple Push Notification Service indicates that it will attempt to deliver a notification to a player.

Confirmed Receipts::
A Confirmed Receipt is tracked when a notification is received and displayed by a device.

Expanded View Imp.::
An Expanded View Impression is tracked when a notification with an expanded view is expanded by the player by force pressing or press-and-holding on the notification.

Clicks::
A click is tracked when a player enters the game through an iOS Push notification. Note that the game must get through complete Teak SDK initialization before a click event will be tracked.

CTR::
iOS Push CTR is clicks / sends as a percentage.

Con. Receipt CTR::
Confirmed Receipt CTR is clicks / confirmed receipts as a percentage.

Returning Users::
include::partial$returning_users.adoc[]

Return Rate::
Return Rate is returning users / confirmed receipts.

Return Value::
include::partial$return_value.adoc[]

Return Spenders::
include::partial$return_spenders.adoc[]

Impact::
Impact is Returning Users for the notification divided by the sum of all sends for all iOS Push notifications.

Avg. Daily Play Time::
The average amount of time spent per day in sessions which started from a click on this notification per player who clicked. +
_(Only available with SDK 4.3 and above.)_

== Android Push

Sends::
A send is tracked when Firebase Cloud Messaging indicates that it will attempt to deliver a notification to a player.

Confirmed Receipts::
A Confirmed Receipt is tracked when a notification is received and displayed by a device.

Clicks::
A click is tracked when a player enters the game through an Android Push notification. Note that the game must get through complete Teak SDK initialization before a click event will be tracked.

CTR::
Android Push CTR is clicks / sends as a percentage.

Con. Receipt CTR::
Confirmed Receipt CTR is clicks / confirmed receipts as a percentage.

Returning Users::
include::partial$returning_users.adoc[]

Return Rate::
Return Rate is returning users / confirmed receipts.

Return Value::
include::partial$return_value.adoc[]

Return Spenders::
include::partial$return_spenders.adoc[]

Impact::
Impact is Returning Users for the notification divided by the sum of all sends for all Android Push notifications.

Avg. Daily Play Time::
The average amount of time spent per day in sessions which started from a click on this notification per player who clicked. +
_(Only available with SDK 4.3 and above.)_

== Email
:channel: email

Sends::
A send is tracked when the configured Email Service Provider indicates that it will attempt to deliver a notification to a player.

Confirmed Receipts::
A Confirmed Receipt is tracked when a receiving mail server confirms receipt of an email.

Opens::
An open is tracked when a player opens and views an email, with image loading enabled.

Unique Opens::
Unique Opens is the count of distinct players each day who opened an email. Note that if you are looking at a time period of, e.g. Jul 16, 2021 - Jul 29, 2021, and the same player opened the same email on Jul 16 and Jul 17, they will be counted as two unique opens for the overall metric.

Open Rate::
Open Rate is opens / sends as a percentage.

Clicks::
A click is tracked when a player enters the game through a link in an email or clicks on the link in an email using an Out of Game URL with the xref:usage::page$email.adoc#_skip_game_open[Skip Game Open, window=_blank] option enabled.

CTR::
Email CTR is clicks / sends as a percentage.

Click to Open Rate::
Click to Open Rate is unique clicks / unique opens as a percentage.

Con. Receipt CTR::
Confirmed Receipt CTR is clicks / confirmed receipts as a percentage.

[[_email_returning_user]]Returning Users::
Returning Users is the count of distinct players each day who entered the game either directly through the email, or within an hour of clicking on the link in an email with the xref:usage::page$email.adoc#_skip_game_open[Skip Game Open, window=_blank] option enabled. +

NOTE: If you are looking at a time period of, e.g. Jul 16, 2021 - Jul 29, 2021, and the same player clicked on the same {channel} on Jul 16 and Jul 17, they will be counted as two returning users for the overall metric.


Return Rate::
Return Rate is returning users / confirmed receipts.

Return Value::
include::partial$return_value.adoc[]

Return Spenders::
include::partial$return_spenders.adoc[]

Impact::
Impact is Returning Users for the notification divided by the sum of all sends for all Emails.

Avg. Daily Play Time::
The average amount of time spent per day in sessions which started from a click on this email per player who clicked. +
_(Only available with SDK 4.3 and above.)_

Bounces::
A bounce is tracked when email delivery fails for a permanent reason, e.g. the email address is invalid or has been deleted.

Bounce Rate::
Bounce Rate is bounces / sends as a percentage.

Blocks::
A block is tracked when email delivery fails for a temporary reason, e.g. the player's email inbox is full.

Unsubscribes::
An unsubscribe is tracked when a player uses the unsubscribe link in the email to unsubscribe from future deliveries.

Spam Reports::
A spam report is tracked when a player marks a received email as spam. Spam reports are _not_ tracked when the receiving mail server's spam filter marks an email as spam.

Unwanted Rate::
Unwanted rate is (unsubscribes + spam reports) / sends as a percentage.

Suppressed for Cold IP::
Suppressed for Cold IP is the count of emails which would have been sent but were instead suppressed due to ongoing IP warmup.
